### PR TITLE
add `recordArtifact`

### PR DESCRIPTION
**Pull request by hjmodi**
* MMENG-3609

### CODE REVIEW

**Comment by sswguo** [comment]
Not sure why I cannot add @yma as a reviewer, @hjmodi  can you try ?

**Comment by hjmodi** [comment]
> Not sure why I cannot add @yma as a reviewer, @hjmodi can you try ?

even I am not able to add her, not sure why

**Comment by hjmodi** [comment]
> Not sure why I cannot add @yma as a reviewer, @hjmodi can you try ?

added her now.

**Review by yma88 — APPROVED** [review]
LGTM

**Pull request merged**
